// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Information about the principal, resource, and permission to check.
public struct AccessTuple: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The principal whose access you want to check, in the form of
  /// the email address that represents that principal. For example,
  /// `alice@example.com` or
  /// `my-service-account@my-project.iam.gserviceaccount.com`.
  ///
  /// The principal must be a Google Account or a service account. Other types of
  /// principals are not supported.
  public var principal: Swift.String = Swift.String()

  /// Required. The full resource name that identifies the resource. For example,
  /// `//compute.googleapis.com/projects/my-project/zones/us-central1-a/instances/my-instance`.
  ///
  /// For examples of full resource names for Google Cloud services, see
  /// https://cloud.google.com/iam/help/troubleshooter/full-resource-names.
  public var fullResourceName: Swift.String = Swift.String()

  /// Required. The IAM permission to check for the specified principal and
  /// resource.
  ///
  /// For a complete list of IAM permissions, see
  /// https://cloud.google.com/iam/help/permissions/reference.
  ///
  /// For a complete list of predefined IAM roles and the permissions in each
  /// role, see https://cloud.google.com/iam/help/roles/reference.
  public var permission: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AccessTuple`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessTuple().with { $0.principal = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let principal = CodingKeys(stringValue: "principal")
    static let fullResourceName = CodingKeys(stringValue: "fullResourceName")
    static let permission = CodingKeys(stringValue: "permission")

    static let _knownKeys: Set<Swift.String> = [
      "principal",
      "fullResourceName",
      "permission",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .principal) {
      self.principal = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fullResourceName) {
      self.fullResourceName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .permission) {
      self.permission = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.principal, forKey: .principal)
    try container.encode(self.fullResourceName, forKey: .fullResourceName)
    try container.encode(self.permission, forKey: .permission)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.v1.AccessTuple"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
