// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Details about how a binding in a policy affects a principal's ability to use
/// a permission.
public struct BindingExplanation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Indicates whether _this binding_ provides the specified
  /// permission to the specified principal for the specified resource.
  ///
  /// This field does _not_ indicate whether the principal actually has the
  /// permission for the resource. There might be another binding that overrides
  /// this binding. To determine whether the principal actually has the
  /// permission, use the `access` field in the
  /// [TroubleshootIamPolicyResponse][IamChecker.TroubleshootIamPolicyResponse].
  public var access: AccessState = AccessState()

  /// The role that this binding grants. For example,
  /// `roles/compute.serviceAgent`.
  ///
  /// For a complete list of predefined IAM roles, as well as the permissions in
  /// each role, see https://cloud.google.com/iam/help/roles/reference.
  public var role: Swift.String = Swift.String()

  /// Indicates whether the role granted by this binding contains the specified
  /// permission.
  public var rolePermission: BindingExplanation.RolePermission = BindingExplanation.RolePermission()

  /// The relevance of the permission's existence, or nonexistence, in the role
  /// to the overall determination for the entire policy.
  public var rolePermissionRelevance: HeuristicRelevance = HeuristicRelevance()

  /// Indicates whether each principal in the binding includes the principal
  /// specified in the request, either directly or indirectly. Each key
  /// identifies a principal in the binding, and each value indicates whether the
  /// principal in the binding includes the principal in the request.
  ///
  /// For example, suppose that a binding includes the following principals:
  ///
  /// * `user:alice@example.com`
  /// * `group:product-eng@example.com`
  ///
  /// You want to troubleshoot access for `user:bob@example.com`. This user is a
  /// principal of the group `group:product-eng@example.com`.
  ///
  /// For the first principal in the binding, the key is
  /// `user:alice@example.com`, and the `membership` field in the value is set to
  /// `MEMBERSHIP_NOT_INCLUDED`.
  ///
  /// For the second principal in the binding, the key is
  /// `group:product-eng@example.com`, and the `membership` field in the value is
  /// set to `MEMBERSHIP_INCLUDED`.
  public var memberships: [Swift.String: BindingExplanation.AnnotatedMembership] = [:]

  /// The relevance of this binding to the overall determination for the entire
  /// policy.
  public var relevance: HeuristicRelevance = HeuristicRelevance()

  /// A condition expression that prevents this binding from granting access
  /// unless the expression evaluates to `true`.
  ///
  /// To learn about IAM Conditions, see
  /// https://cloud.google.com/iam/help/conditions/overview.
  public var condition: GoogleType.Expr? = nil

  /// Initialize a new instance of `BindingExplanation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BindingExplanation().with { $0.access = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Details about whether the binding includes the principal.
  public struct AnnotatedMembership: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Indicates whether the binding includes the principal.
    public var membership: BindingExplanation.Membership = BindingExplanation.Membership()

    /// The relevance of the principal's status to the overall determination for
    /// the binding.
    public var relevance: HeuristicRelevance = HeuristicRelevance()

    /// Initialize a new instance of `AnnotatedMembership`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnnotatedMembership().with { $0.membership = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.policytroubleshooter.v1.BindingExplanation.AnnotatedMembership"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Whether a role includes a specific permission.
  public enum RolePermission: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The permission is included in the role.
    case included
    /// The permission is not included in the role.
    case notIncluded
    /// The sender of the request is not allowed to access the binding.
    case unknownInfoDenied
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .included: return 1
      case .notIncluded: return 2
      case .unknownInfoDenied: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ROLE_PERMISSION_UNSPECIFIED"
      case .included: return "ROLE_PERMISSION_INCLUDED"
      case .notIncluded: return "ROLE_PERMISSION_NOT_INCLUDED"
      case .unknownInfoDenied: return "ROLE_PERMISSION_UNKNOWN_INFO_DENIED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RolePermission/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ROLE_PERMISSION_UNSPECIFIED": self = .unspecified
      case "ROLE_PERMISSION_INCLUDED": self = .included
      case "ROLE_PERMISSION_NOT_INCLUDED": self = .notIncluded
      case "ROLE_PERMISSION_UNKNOWN_INFO_DENIED": self = .unknownInfoDenied
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RolePermission/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .included
      case 2: self = .notIncluded
      case 3: self = .unknownInfoDenied
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .included: return try container.encode(1)
      case .notIncluded: return try container.encode(2)
      case .unknownInfoDenied: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Whether the binding includes the principal.
  public enum Membership: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The binding includes the principal. The principal can be included
    /// directly or indirectly. For example:
    ///
    /// * A principal is included directly if that principal is listed in the
    ///   binding.
    /// * A principal is included indirectly if that principal is in a Google
    ///   group or Google Workspace domain that is listed in the binding.
    case included
    /// The binding does not include the principal.
    case notIncluded
    /// The sender of the request is not allowed to access the binding.
    case unknownInfoDenied
    /// The principal is an unsupported type. Only Google Accounts and service
    /// accounts are supported.
    case unknownUnsupported
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .included: return 1
      case .notIncluded: return 2
      case .unknownInfoDenied: return 3
      case .unknownUnsupported: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MEMBERSHIP_UNSPECIFIED"
      case .included: return "MEMBERSHIP_INCLUDED"
      case .notIncluded: return "MEMBERSHIP_NOT_INCLUDED"
      case .unknownInfoDenied: return "MEMBERSHIP_UNKNOWN_INFO_DENIED"
      case .unknownUnsupported: return "MEMBERSHIP_UNKNOWN_UNSUPPORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Membership/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MEMBERSHIP_UNSPECIFIED": self = .unspecified
      case "MEMBERSHIP_INCLUDED": self = .included
      case "MEMBERSHIP_NOT_INCLUDED": self = .notIncluded
      case "MEMBERSHIP_UNKNOWN_INFO_DENIED": self = .unknownInfoDenied
      case "MEMBERSHIP_UNKNOWN_UNSUPPORTED": self = .unknownUnsupported
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Membership/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .included
      case 2: self = .notIncluded
      case 3: self = .unknownInfoDenied
      case 4: self = .unknownUnsupported
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .included: return try container.encode(1)
      case .notIncluded: return try container.encode(2)
      case .unknownInfoDenied: return try container.encode(3)
      case .unknownUnsupported: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.v1.BindingExplanation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
