// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleIAMV1

/// Details about how a specific IAM [Policy][google.iam.v1.Policy] contributed
/// to the access check.
///
/// [google.iam.v1.Policy]: https://www.google.com/search?q=Swift+google.iam.v1+GoogleIAMV1.Policy
public struct ExplainedPolicy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Indicates whether _this policy_ provides the specified permission to the
  /// specified principal for the specified resource.
  ///
  /// This field does _not_ indicate whether the principal actually has the
  /// permission for the resource. There might be another policy that overrides
  /// this policy. To determine whether the principal actually has the
  /// permission, use the `access` field in the
  /// [TroubleshootIamPolicyResponse][IamChecker.TroubleshootIamPolicyResponse].
  public var access: AccessState = AccessState()

  /// The full resource name that identifies the resource. For example,
  /// `//compute.googleapis.com/projects/my-project/zones/us-central1-a/instances/my-instance`.
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is omitted.
  ///
  /// For examples of full resource names for Google Cloud services, see
  /// https://cloud.google.com/iam/help/troubleshooter/full-resource-names.
  public var fullResourceName: Swift.String = Swift.String()

  /// The IAM policy attached to the resource.
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is empty.
  public var policy: GoogleIAMV1.Policy? = nil

  /// Details about how each binding in the policy affects the principal's
  /// ability, or inability, to use the permission for the resource.
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is omitted.
  public var bindingExplanations: [BindingExplanation] = []

  /// The relevance of this policy to the overall determination in the
  /// [TroubleshootIamPolicyResponse][IamChecker.TroubleshootIamPolicyResponse].
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is omitted.
  public var relevance: HeuristicRelevance = HeuristicRelevance()

  /// Initialize a new instance of `ExplainedPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExplainedPolicy().with { $0.access = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.v1.ExplainedPolicy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
