// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class IamCheckerTransport: IamCheckerStub {
    let inner: GoogleGax._HTTPClient

    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      self.inner = try GoogleGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://policytroubleshooter.googleapis.com",
      )
    }

    @concurrent
    public func troubleshootIamPolicy(
      request: TroubleshootIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPolicyTroubleshooterV1.TroubleshootIamPolicyResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          let path = "/v1/iam:troubleshoot"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          paths.append(GoogleGax.PathMismatch())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleCloudPolicyTroubleshooterV1.TroubleshootIamPolicyResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }
  }
}
