// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class IamCheckerLogging: IamCheckerStub {
    let inner: any IamCheckerStub
    let logger: Logger

    public init(_ inner: any IamCheckerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-policytroubleshooter-v1"
      logger[metadataKey: "gcp.client.service"] = "policytroubleshooter"
      logger[metadataKey: "gcp.experimental.swift.client"] = "IamChecker"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func troubleshootIamPolicy(
      request: TroubleshootIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPolicyTroubleshooterV1.TroubleshootIamPolicyResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "troubleshootIamPolicy",
        action: {
          (r: TroubleshootIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudPolicyTroubleshooterV1.TroubleshootIamPolicyResponse
          in
          return try await self.inner.troubleshootIamPolicy(request: r, options: o)
        })
    }
  }
}
