// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// Response for
/// [TroubleshootIamPolicy][google.cloud.policytroubleshooter.v1.IamChecker.TroubleshootIamPolicy].
///
/// [google.cloud.policytroubleshooter.v1.IamChecker.TroubleshootIamPolicy]: <doc:IamCheckerClient/troubleshootIamPolicy(request:options:)>
public struct TroubleshootIamPolicyResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Indicates whether the principal has the specified permission for the
  /// specified resource, based on evaluating all of the applicable IAM policies.
  public var access: AccessState = AccessState()

  /// List of IAM policies that were evaluated to check the principal's
  /// permissions, with annotations to indicate how each policy contributed to
  /// the final result.
  ///
  /// The list of policies can include the policy for the resource itself. It can
  /// also include policies that are inherited from higher levels of the resource
  /// hierarchy, including the organization, the folder, and the project.
  ///
  /// To learn more about the resource hierarchy, see
  /// https://cloud.google.com/iam/help/resource-hierarchy.
  public var explainedPolicies: [ExplainedPolicy] = []

  /// The general errors contained in the troubleshooting response.
  public var errors: [GoogleRpc.Status] = []

  /// Initialize a new instance of `TroubleshootIamPolicyResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TroubleshootIamPolicyResponse().with { $0.access = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.v1.TroubleshootIamPolicyResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
